// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AiAnalysisLog
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string AnalysisResult { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AiAnalysisProduct> AiAnalysisProducts { get; set; } = new List<AiAnalysisProduct>();

    public virtual User User { get; set; }
}