// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AiAnalysisProduct
{
    public Guid Id { get; set; }

    public Guid? AianalysisId { get; set; }

    public Guid? ProductId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual AiAnalysisLog Aianalysis { get; set; }

    public virtual SuggestedProduct Product { get; set; }
}