// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class DailyRoutine
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string RoutineDetails { get; set; }

    public string SuggestedProducts { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<DailyRoutineProduct> DailyRoutineProducts { get; set; } = new List<DailyRoutineProduct>();

    public virtual User User { get; set; }
}