// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class PaymentLog
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public Guid? VippackageId { get; set; }

    public string TransactionId { get; set; }

    public string PaymentStatus { get; set; }

    public decimal PaymentAmount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }

    public virtual VipPackage Vippackage { get; set; }
}