// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class UserVip
{
    public Guid UserId { get; set; }

    public Guid VippackageId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public virtual User User { get; set; }

    public virtual VipPackage Vippackage { get; set; }
}