// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Repository.Enums;

namespace Repository.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public UserRole Role { get; set; }

    public bool? IsActive { get; set; }

    public string ProfilePicture { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AiAnalysisLog> AiAnalysisLogs { get; set; } = new List<AiAnalysisLog>();

    public virtual ICollection<BlogComment> BlogComments { get; set; } = new List<BlogComment>();

    public virtual ICollection<DailyRoutine> DailyRoutines { get; set; } = new List<DailyRoutine>();

    public virtual ICollection<PaymentLog> PaymentLogs { get; set; } = new List<PaymentLog>();

    public virtual ICollection<UserVip> UserVips { get; set; } = new List<UserVip>();
}